import { montserrat, montserratAlternates, medieval } from "./fonts";
import "./globals.css";
import SmoothScrollProvider from "@/components/smooth-scroll-provider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserratAlternates.variable} ${medieval.variable}  antialiased relative`}
      >
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
